// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Primatives$ReactHooksTemplate = require("./Primatives.bs.js");

function Example(Props) {
  return React.createElement("div", undefined, React.createElement(Primatives$ReactHooksTemplate.$$Text[/* make */0], {
                  px: 3,
                  size: 80,
                  children: "Sup mang"
                }), React.createElement(Primatives$ReactHooksTemplate.Box[/* make */0], {
                  px: 30,
                  mt: 2,
                  children: React.createElement("div", undefined)
                }));
}

var make = Example;

exports.make = make;
/* react Not a pure module */
