// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Example$ReactHooksTemplate = require("./Example.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Example$ReactHooksTemplate.make, { }), "example");

/*  Not a pure module */
