// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Css = require("@astrada/bs-css-core/src/Css.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function BoxMaker(Config) {
  var Factories$BoxMaker = function (Props, children) {
    Props.py;
    Props.px;
    Props.p;
    var match = Props.mt;
    var mt = match !== undefined ? match : 0;
    Props.mb;
    Props.ml;
    Props.mr;
    var match$1 = Props.style;
    if (match$1 !== undefined) {
      Caml_option.valFromOption(match$1);
    } else {
      Css.style(/* [] */0);
    }
    return React.createElement("div", {
                style: {
                  marginTop: mt === 5 ? String(Caml_array.caml_array_get(Config[/* scale */0], 5)) : (
                      mt === 4 ? String(Caml_array.caml_array_get(Config[/* scale */0], 4)) : (
                          mt === 3 ? String(Caml_array.caml_array_get(Config[/* scale */0], 3)) : (
                              mt === 2 ? String(Caml_array.caml_array_get(Config[/* scale */0], 2)) : (
                                  mt === 1 ? String(Caml_array.caml_array_get(Config[/* scale */0], 1)) : String(mt)
                                )
                            )
                        )
                    )
                }
              }, children);
  };
  return /* module */[
          /* beep */"",
          /* make */Factories$BoxMaker
        ];
}

exports.BoxMaker = BoxMaker;
/* react Not a pure module */
