// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Box$ReactHooksTemplate = require("./Box.bs.js");
var Scale$ReactHooksTemplate = require("./Scale.bs.js");

var Box = Box$ReactHooksTemplate.BoxMaker(/* module */[/* scale */Scale$ReactHooksTemplate.space]);

exports.Box = Box;
/* Box Not a pure module */
