// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var space = /* array */[
  2,
  4,
  8,
  16,
  32
];

var font = /* array */[
  2,
  4,
  8,
  16,
  32
];

var Scale = /* module */[
  /* space */space,
  /* font */font
];

var Units = /* module */[/* px */"px"];

exports.Scale = Scale;
exports.Units = Units;
/* No side effect */
